insert into categories
values 
    (1,'Television'),
    (2,'Film'),
    (3,'Short Film'),
    (4,'Documentary'),
    (5,'Online'),
    (6,'Technical Craft');

insert into presenting_partners
values 
    (1,'EMG/Gravity Media'),
    (2,'Network 10'),
    (3,'BINGE'),
    (4,'Spectrum Films'),
    (5,'Casting Networks'),
    (6,'Foxtel');

insert into awards (award_name,category_id)
values 
    ('Best Drama Series',1),
    ('Best Miniseries',1),
    ('Best Narrative Comedy Series',1),
    ('Best Comedy Entertainment Program',1),
    ('Best Entertainment Program',1),
    ('Best Factual Entertainment Program',1),
    ('Best Lifestyle Program',1),
    ('Best Reality Program',1),
    ('Best Documentary or Factual Program',1),
    ('Best Children''s Program',1),
    ('Best Stand-Up Special',1),
    ('Best Lead Actress in a Drama',1),
    ('Best Lead Actor in a Drama',1),
    ('Best Comedy Performer',1),
    ('Best Acting in a Comedy',1),
    ('Best Supporting Actress in a Drama',1),
    ('Best Supporting Actor in a Drama',1),
    ('Best Direction in Drama or Comedy',1),
    ('Best Screenplay in Television',1),
    ('Best Direction in Nonfiction Television',1),
    ('Best Cinematography in Television',6),
    ('Best Costume Design in Television',6),
    ('Best Editing in Television',6),
    ('Best Production Design in Television',6),
    ('Best Original Score in Television',6),
    ('Best Sound in Television',6),
    ('Best Casting in Television',6);

insert into distribution_companies (distribution_co_name)
values 
    ('Paramount+'),
    ('Netflix'),
    ('Disney+'),
    ('Foxtel'),
    ('Binge'),
    ('Stan'),
    ('ABC'),
    ('SBS'),
    ('Nine Network'),
    ('Amazon Prime Video');

insert into production_companies (production_co_name)
values 
    ('Kindling Pictures'),
    ('Fremantle Australia'),
    ('Curio Pictures'),
    ('Beach Road Pictures'),
    ('Warner Bros. International Television Production Australia'),
    ('Easy Tiger Productions'),
    ('Ludo Studio & Since1778 Productions'),
    ('Blackfella Films'),
    ('Brouhaha Entertainment Australia'),
    ('Thirdborn'),
    ('Matchbox Pictures'),
    ('Roadshow Rough Diamond'),
    ('Princess Pictures'),
    ('Northern Pictures'),
    ('Origma 45'),
    ('BBC Studios Australia'),
    ('Bunya Entertainment'),
    ('Made Up Stories'),
    ('Fifth Season'),
    ('Working Dog Productions'),
    ('Thinkative Television'),
    ('ABC'),
    ('Kevin & Co'),
    ('Endemol Shine Australia');


insert into talents (talent_fname,talent_lname)
values 
    ('Imogen', 'Banks'),
    ('Emelyne', 'Palmer'),
    ('Asher', 'Keddie'),
    ('Carly', 'Heaton'),
    ('Sarah', 'Freeman'),
    ('Hannah Carroll', 'Chapman'),
    ('Jo', 'Porter'),
    ('David', 'Maher'),
    ('David', 'Taylor'),
    ('Hamish', 'Lewis'),
    ('Michael','Brooks'),
    ('Dylan', 'River'),
    ('Darren', 'Dale'),
    ('Andrew', 'Mason'),
    ('Ally', 'Henville'),
    ('Ian', 'Collie'),
    ('Rob', 'Gibson'),
    ('Tanith', 'Glynn-Maloney'),
    ('Charlie', 'Aspinwall'),
    ('Daley', 'Pearson'),
    ('Sam', 'Moor'),
    ('Rachel', 'Griffiths'),
    ('Stuart', 'Page'),
    ('Erin', 'Bretherton'),
    ('Nikki', 'Barrett'),
    ('Kirsty', 'McGregor'),
    ('Stevie', 'Ray'),
    ('Nathan', 'Lloyd'),
    ('Leigh', 'Pickford'),
    ('Deborah', 'Mailman'),
    ('Leah', 'Purcell'),
    ('Phoebe', 'Tonkin'),
    ('Anna', 'Torv'),
    ('Sherry-Lee', 'Watson'),
    ('Zac', 'Burgess'),
    ('Felix', 'Cameron'),
    ('Rob', 'Collins'),
    ('Brendan', 'Cowell'),
    ('Sam', 'Neill'),
    ('Noah', 'Taylor'),
    ('Shelley','Farthing-Dawe'),
    ('Mark', 'Wareham'),
    ('Aaron', 'McLisky'),
    ('Simon', 'Duggan'),
    ('Tyson', 'Perkins'),
    ;


insert into productions (production_name)
values 
    ('Boy Swallows Universe'),
    ('Colin From Accounts'),
    ('Fake'),
    ('The Artful Dodger'),
    ('The Twelve'),
    ('Heartbreak High'),
    ('Thou Shalt Not Steal'),
    ('Total Control'),
    ('Plum'),
    ('High Country'),
    ('Territory'),
    ('Exposure')
    ;

insert into nominations (award_id, talent_id, production_id)
values 
    (1,1,3),
    (1,2,3),
    (1,3,3),
    (1,4,6),
    (1,5,6),
    (1,6,6),
    (1,7,4),
    (1,8,4),
    (1,9,4),
    (1,10,5),
    (1,11,5),
    (1,15,5),
    (1,16,5),
    (1,17,5),
    (1,12,7),
    (1,18,7),
    (1,19,7),
    (1,20,7),
    (1,21,7),
    (1,13,8),
    (1,22,8),
    (1,23,8),
    (1,24,8),
    (27,25,1),
    (27,26,2),
    (27,27,2),
    (27,28,3),
    (27,29,4),
    (27,30,5),
    (21,41,1),
    (21,42,1),
    (21,43,12),
    (21,44,11),
    (21,45,7),
    (12,3,3),
    (12,30,8),
    (12,31,10),
    (12,32,1),
    (12,33,11),
    (12,34,7),
    (13,35,1),
    (13,36,1),
    (13,37,8),
    (13,38,9),
    (13,39,5),
    (13,40,7)
    ;

